config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'
  mount ActionCable.server => '/cable'

  get '/share' => 'movies#new'
  post '/sign_in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :movies, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user

  validates :youtube_url, youtube_link_format: true, presence: true
  validates :youtube_id, :title, presence: true
  validates :youtube_id, uniqueness: {case_sensitive: true}
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  include BCrypt

  has_many :movies, dependent: :destroy

  validates :email, email: true, presence: true
  validates :encrypted_password, presence: true

  def password
    @password ||= Password.new encrypted_password
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.encrypted_password = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include WardenHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate!, only: %i[new create]

  DEFAULT_PERPAGE = 3

  def index
    @movies = Movie.order(created_at: :desc).page(params[:page]).per(DEFAULT_PERPAGE)
  end

  def new
    @movie = Movie.new
  end

  def create
    movie_service = MovieService.new(movie_params[:youtube_url])
    @movie = Movie.new(movie_service.infor)
    @movie.youtube_url = movie_params[:youtube_url]
    @movie.user = current_user
    if @movie.save
      flash[:success] = 'Share movie successfully'
      NotifyNewMovieJob.perform_later(current_user, @movie)
      redirect_to :root
    else
      flash[:danger] = 'Your movie is invalid'
      redirect_to '/share'
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:youtube_url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    if login || create_user_for_first_time?
      flash[:success] = 'Login successfully'
    elsif @user&.errors&.messages.present?
      flash[:danger] = "Email #{@user.errors.messages[:email].first}"
    end
    redirect_to :root
  end

  def destroy
    warden.logout
    flash[:success] = 'Logout successfully'
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:email, :encrypted_password)
  end

  def login
    User.exists?(email: user_params[:email]) && authenticate!
  end

  def create_user_for_first_time?
    return if User.exists?(email: user_params[:email])

    @user = User.new(user_params)
    @user.password = user_params[:encrypted_password] if user_params[:encrypted_password].present?
    warden.set_user(@user) if @user.save
  end
end

app/controllers/unauthorized_controller.rb
class UnauthorizedController < ApplicationController
  class << self
    def call(env)
      @respond ||= action :respond
      @respond.call env
    end
  end

  def respond
    flash[:danger] = request.env['warden.options'].fetch(:message, "unauthorized.user") unless request.get?
    redirect_to root_url
  end
end

app/controllers/warden_helper.rb
module WardenHelper
  extend ActiveSupport::Concern

  included do
    helper_method :warden, :signed_in?, :current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    User.find(warden.user['id']) if warden.user
  end

  def warden
    request.env['warden']
  end

  def authenticate!
    warden.authenticate!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.slim
footer.page-footer.font-small.blue
  .footer-copyright.text-center.py-3
    | Copyright © 2023 Copyright by VIDEO SHARING

app/views/layouts/_header.html.slim
.topnav
  h1
    i.fa.fa-home
    = link_to 'VIDEO SHARING', root_path, class: 'home-url'
  .login-container
    - unless signed_in?
      = form_with model: User.new, url: sign_in_path, id: 'new_user' do |f|
        = f.email_field :email, required: true, class: 'input-form', placeholder: 'email'
        = f.password_field :encrypted_password, required: true, class: 'input-form', placeholder: 'password'
        = f.submit 'Login / Register', class: 'button'
    - else
      span.welcome
        | Welcome
      span
        = current_user.email
      = link_to 'Share more video', share_path, class: 'button share-video'
      = link_to 'Log out', logout_path, data: { "turbo-method": :delete }, class: 'button log-out'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | VIDEO SHARING
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload'
    = javascript_importmap_tags 'application'
  body
    .container
      = render 'layouts/header'
      - flash.each do |key, value|
        |  <div class="alert alert-
        = key
        | ">
        = value
    .main-content
      = yield
    = render 'layouts/share/notify'
    = render 'layouts/footer'

app/views/layouts/share/_notify.html.slim
#notify.modal.fade[tabindex="-1" role="dialog" aria-labelledby="notify" aria-hidden="true"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        h5#notify.modal-title
          | New movie
        button.close[type="button" data-bs-dismiss="modal" aria-label="Close"]
          i.fa.fa-close
      .modal-body
        p
          strong
            | Shared by: 
          span.notify-email
        p
          strong
            | Description: 
          a.notify-title[target="_blank"]

app/views/movies/_form.html.slim
div class='row justify-content-md-center'
  = form_with model: @movie, class: 'form-video col-md-6', id: 'new_movie' do |f|
    span class='title'
      | Share a youtube video
    div class='row you-url-wrap'
      = f.label :youtube_url, 'Youtube URL: ', class: 'col-md-4 input-label'
      = f.text_field :youtube_url, class: 'col-md-6 input-form'
    div class='row'
      = f.submit 'Share', class: 'col-md-6 offset-md-4 button'

app/views/movies/_movie.html.slim
div class='row movie-container'
  div class='col-md-4 offset-md-1'
    iframe allowfullscreen="" frameborder="0" height="255" src="https://www.youtube.com/embed/#{movie.youtube_id}" width="450" 
  div class='col-md-4 offset-md-1'
    p class='title'
      a href="#{movie.youtube_url}"
        = movie.title
    p class='email'
      | Shared by: 
      = movie.user.email
    p class='description'
      | Description: 
      br
      span = movie.description

app/views/movies/index.html.slim
- if @movies.any?
  - @movies.each do |movie|
    = render partial: 'movie', locals: { movie: movie }
  = paginate @movies

app/views/movies/new.html.slim
= render 'form'